### ISSUE TITLE
Redundant parantheses with metro

### ISSUE THREAD

**Issue by Netzwerk2** [sjfhsjfh/slashion#1]
I'm not sure if this is an issue with slashion or metro :)
When using units with more than one letter, the unit is surrounded with parantheses, which are not necessary.

```typst
#import "@preview/slashion:0.1.0": slash-frac
#import "@preview/metro:0.3.0": *

#show math.equation.where(block: false): slash-frac
#metro-setup(per-mode: "fraction")

$qty(1.197, "kg / m^3")$
```
![image](https://github.com/user-attachments/assets/b8919fc7-9a53-4c16-a8fc-f3c7a910af3d)

**Comment by sjfhsjfh** [comment]
Added an option, you may wait for 0.1.1.

**Comment by sjfhsjfh** [comment]
Already merged https://github.com/typst/packages/pull/1266

**Comment by Netzwerk2** [comment]
Thanks. However there's a case, where this isn't feasible. e.g. if I have kJ / (kg K). I want the parentheses to be at the denominator but not the numerator.

I found out that the issue is how metro combines prefixes and units.
As a simple reproducible example `("k""J") / ("K")` uses parentheses for the numerator, but `(#[kJ]) / ("K")` does not.
I don't think it's possible to fix this behaviour in slashion, though (especially if kJ is in the denomiator). For the numerator one could possibly determine whether it consists of an addition/subtraction. However, for the denominator there's no way of knowing if `"k""J"` is supposed to be one element or two. So I guess, I need to play a bit with the metro source code :)

**Comment by sjfhsjfh** [comment]
You're right, the difference here is that `"k""J"` is a `sequence` while `#[kJ]` is a `text`, so what you need is to modify metro's behaviour to make it show single unit text in a text element. This can be done in Typst I guess.

However, I see the neccessity for dealing with sequences since the unit could be in the form of 10^-3 m or something like this. So I provided an option to turn off the auto `()` pair. You may manually add it into you denominator by modifying metro generated units.
